### PR TITLE
Fix for issue #4

### LINKED ISSUE #4: If temporary clause skipped
I forked your repo and while I was using it I found bug - during updating incremental models dbt cannot create temporary table for increment.

[`{% if is_partition %}`](https://github.com/markporoshin/dbt-greenplum/blob/39dcfe0e03f4cd0639932f81984c74f6d8778c91/dbt/include/greenplum/macros/adapters.sql#L30)
should be `{% if is_partition and not temporary %}` [like this](https://github.com/markporoshin/dbt-greenplum/pull/5/commits/0171d75b046d725cf5501c79ac6cf901bbb538e4)

### PR DESCRIPTION
**Pull request by d1bevz**
Fixes [this issue](https://github.com/markporoshin/dbt-greenplum/issues/4)

### CODE REVIEW

**Comment by markporoshin** [comment]
Hi, i've switched general branch from main to develop

File: dbt/include/greenplum/macros/adapters.sql [hunk 1]
```diff
@@ -122,6 +122,21 @@
   ({{ comma_separated_columns }});
 {%- endmacro %}
 
+{% macro greenplum__generate_schema_name(custom_schema_name, node) -%}
```
Comment (markporoshin) [inline dbt/include/greenplum/macros/adapters.sql:125]: Hi! Could you explain the reason for this macro? I don't see this macro here https://docs.getdbt.com/docs/contributing/building-a-new-adapter
If you want to specify schema, you can write something like that:
```
{{
    config(
        schema='<schema_name>',
    )
}}
```

File: dbt/include/greenplum/macros/adapters.sql [hunk 2]
```diff
@@ -27,7 +27,7 @@
 
   {{ sql_header if sql_header is not none }}
 
-  {% if is_partition %}
+  {% if is_partition and not temporary %}
```
Comment (markporoshin) [inline dbt/include/greenplum/macros/adapters.sql:30]: Thank you!)

File: dbt/include/greenplum/macros/adapters.sql (hunk 1 above)
Comment (d1bevz) [reply dbt/include/greenplum/macros/adapters.sql:125]: Native dbt-function would compile target schema name as a compilation `{profile.schema}_{project.schema}`
That means that every custom schema should has schema name from your profile.yml

For example if I have `schema: public` in profiles.yml
And than I specify schema in model's config, let's say `config(schema='my_data_marts')`
Compiled SQL will be `select * from public_my_data_marts.table_name`

I don't know if someone uses this as naming convension.

Comment (d1bevz) [reply dbt/include/greenplum/macros/adapters.sql:125]: I just dropped the `{profile.schema}_` in the `{profile.schema}_{project.schema}`

So that compiled sql from my example would be `select * from my_data_marts.table_name`

Comment (markporoshin) [reply dbt/include/greenplum/macros/adapters.sql:125]: You are right! We are dealing with it by setting up some prefix in our profile.yml. Thank you)

Comment (d1bevz) [reply dbt/include/greenplum/macros/adapters.sql:125]: We have over 600+ sources - would be overkill to store 600+ similar profiles)

Comment (markporoshin) [reply dbt/include/greenplum/macros/adapters.sql:125]: Haha

I've updated package on pypi https://pypi.org/project/dbt-greenplum/1.0.4.1/
